### ISSUE TITLE
error due to new classname, when using: mllaunchpad -c config_dev train 

### ISSUE THREAD

**Issue by TheMBadger** [schuderer/mllaunchpad#115]
Situation is:
1. I have trained a model.
2. I change my class name afterwards (it was MyExampleModel)
3. I train again via: mllaunchpad -c config_dev -train

My Expectation: A new model is trained
What really happens: I get an error because of my old model.
Workaround: Throw away my old model first

Suggestion: ignore old model

**Comment by schuderer** [comment]
Thanks for reporting. I regard this as a bug. Should be a quick fix. I added it to the list of items under prioritization.
