### ISSUE TITLE
Typo in https://mllaunchpad.readthedocs.io/en/stable/changelog.html

### ISSUE THREAD

**Issue by TheMBadger** [schuderer/mllaunchpad#150]
### Description

small typo in changelog

### Steps to reproduce
1. Go to: https://mllaunchpad.readthedocs.io/en/stable/changelog.html
2. See title: 1.0.0 (2021-12-13)

should be: 1.1.0 (2021-12-13)
```

**Comment by TheFenrisLycaon** [comment]
I can fix it. I'm bored anyways :)

**Comment by schuderer** [comment]
Awesome @TheFenrisLycaon! PR welcome. :)
https://mllaunchpad.readthedocs.io/en/stable/contributing.html
