### ISSUE TITLE
improve contribution documentation

### ISSUE THREAD

**Issue by schuderer** [schuderer/mllaunchpad#35]
Missing info in CONTRIBUTING:
- how to activate the environment (``$ pipenv shell``, see README)
- setting the upstream and refreshing/pulling from it: from https://scikit-learn.org/dev/developers/contributing.html
- using google style, particularly docstrings: https://google.github.io/styleguide/pyguide.html#381-docstrings

```
Add the upstream remote. This saves a reference to the main scikit-learn
repository, which you can use to keep your repository synchronized
with the latest changes:

$ git remote add upstream https://github.com/scikit-learn/scikit-learn.git

...

It is often helpful to keep your local branch synchronized with the latest
changes of the main scikit-learn repository:

$ git fetch upstream
$ git merge upstream/master
```

NOTE: it's preferrable to (if possible) rebase instead of merging (merging creates a lot of meaningless merge commits). In our doc, the last suggested command should probably be:
```sh
$ git rebase upstream/master
```

**Comment by gosiarorat** [comment]
i am taking the issue
