### ISSUE TITLE
Impala support (Hadoop)

### ISSUE THREAD

**Issue by schuderer** [schuderer/mllaunchpad#4]

**Comment by ghost** [comment]
@schuderer Ik ben niet veel verder gekomen en zit vast ermee. 
Graag hulp/suggesties bij nodig....zou fijn zijn als we dit kunnen oplossen :) 

Stack:      impyla	    0.15.0
		PyHive	    0.6.1	
		thrift	            0.13.0	
		thrift-sasl     0.4a1	
		thriftpy	    0.3.9	
		thriftpy2	    0.4.0 
			
Code:
from impala.dbapi import connect
conn = connect(host='xxxxxx.xxxx.net', port=8888,kerberos_service_name='impala')
conn.cursor()
'xxxxxx.xxxx.net' = bda host

Error:
impala.error.HiveServer2Error: Failed after retrying 3 times

**Comment by schuderer** [comment]
Thanks @planeetjupyter! Hard to pinpoint what to search for without knowing whether the error happens at the `connect()` line or at the `conn.cursor()` line. I assume it happens at `conn.cursor()`.

I suppose you already did do the google on this. I any case, does this match the problem and might there be pointers for us: https://github.com/cloudera/impyla/issues/252. Might these be  some tipps on what to try out?
> Are you able to SSH into this machine to run any query through impala-shell without explicitly being the impala user ; and/or belonging to an impala group?
> To help others: It was a authentication issue. I added auth_mechanism='PLAIN'.

Maybe not because this person is not using Kerberos, but I'm not sure whether this is a connection problem or an authentication problem.

Anything in here https://github.com/cloudera/impyla/issues?utf8=%E2%9C%93&q=HiveServer2Error%3A+Failed+after+retrying+3+times ?

**Comment by schuderer** [comment]
This does not work in Oracle Big Data Appliance for some reason.

**Comment by joosbuijsNL** [comment]
Might be out of our control and an issue at the BDA side.

@schuderer  maybe you can report this at https://github.com/cloudera/impyla/issues/338 and see if they are willing/able to help further if we provide additional info?

Happy to help out where possible!

**Comment by schuderer** [comment]
In PR #121 , I'm currently working on a generic `SQLDataSource` implementation for SQL-based databases (which will be based on SQLAlchemy). This will also allow for ODBC connections, among others.

As such, this will make it possible to connect to Impala using the Oracle Impala ODBC Drivers. Therefore, this issue here will be closed when PR #121 is done.

Feel free to reopen if there are any more insights, such as any response at cloudera/impyla#338 and/or  specific requirements for non-ODBC impala connections.
