### ISSUE TITLE
Relative file references in config should be relative to path of config file

### ISSUE THREAD

**Issue by schuderer** [schuderer/mllaunchpad#40]
Currently, this affects `api.raml:`, `datasource:...:path:` (for file DataSources), and the R bridge's `model:r_file` (code currently located in examples/r_example.py).

Probably just need some good, consistent use of the robust functionality which `os.path` offers.

Please note that *module* references (like those under the optional `plugins:` key, or `model.module:`) are *not* file references and therefore not in scope for this issue.

**Comment by planeetjupyter** [comment]
Ik wil deze wel oppakken, kan je mijn username vastzetten hierop?
Mvg, Elisa

**Comment by schuderer** [comment]
When tackling `yaml-loader.py`, it still needs to be adapted (expand the path.split()[0] to an absolute path before assigning to self._root). So this: https://github.com/schuderer/mllaunchpad/blob/394ec33f9a8847607dd1ea58925f6a0c73afe87b/mllaunchpad/yaml_loader.py#L9 becomes this:
```python
abs_path = os.path.abspath(stream.name)
self._root = os.path.split(abs_path)[0]
```
Also find a way to make top-level loader's self._root available in the config as "root:" if not exists (and if possible, if someone sets "root:" manually, use it as root for everything, including the _root property of the main yaml loader)

**Comment by ghost** [comment]
Thanks for the feedback, I will take it along and update the code.

**Comment by schuderer** [comment]
@planeetjupyter  No need, the code from your previous PR is fine. This issue is about a different task than the modularization-issue you solved, and it’s actually better to keep those separate. My comment is just a reminder for what to think of when issue #40 is eventually picked up,

Edit: unless of course you want to pick up this issue here. :)

**Comment by schuderer** [comment]
I'm actually not sure any more whether this is a good idea. I took this idea from the nginx `root` path. But on further introspection I came to the conclusion that, when people specify relative paths, they usually expect them to work relative to the current working directory.
