### ISSUE TITLE
Correcting variable names in TEMPLATE_cfg.yml 

### ISSUE THREAD

**Issue by Bart92** [schuderer/mllaunchpad#43]
* ML Launchpad version: 0.0.5
* Model Type used: Python
* DataSource type(s) used: csv
* Python version: 3.6.5
* Operating System: iOS

### Description

I noticed that all variables related to the model are still called "Some" referring to a previous file name that was assigned to the Template model.
Very minor issue but great as a first issue to pick up :)
PS: it says * ML Launchpad version:  but you need to run `mllaunchpad --version`

### What I Did

I adjusted it locally for now but if you agree with me adjusting it I'll clone the repo and then commit / push it.

**Comment by schuderer** [comment]
@Bart92 Thanks for reporting! A fix for this is very welcome! Only project maintainers can push to the repo directly, but if you want to create a pull request, that would be great (see `CONTRIBUTING` for details). If you have any questions, I'm here to help.

P.S.: You can skip steps 3 and 5 of the `CONTRIB` guideline if the changes are only in the template.
