### ISSUE TITLE
Misleading error message "mllaunchpad.wsgi: Config file could not be loaded"

### ISSUE THREAD

**Issue by schuderer** [schuderer/mllaunchpad#61]
This error also occurs if loading a previous model fails during the the ModelApi initialization. The try-catch block in the wsgi module mistakenly assumes that FileNotFoundError can only occur when loading the config, but it can also occur on initializing ModelApi (if the model could not be loaded from the model store). See:

https://github.com/schuderer/mllaunchpad/blob/cc378e1f1935d5211addf385075323a68253e746/mllaunchpad/wsgi.py#L33

Should probably be handled separately.

**Comment by bobplatte** [comment]
I will work on this issue.

**Comment by schuderer** [comment]
Thanks Bob!

There was a mistake in the issue description, it said „The try-catch block in the wsgi module mistakenly assumes that FileNotFoundError can only occur when loading the **api**.“

I edited it to say: „The try-catch block in the wsgi module mistakenly assumes that FileNotFoundError can only occur when loading the **config, but it can also occur on initializing ModelApi (if the model could not be loaded from the model store)**“
